- name: Create server instances
  


- name: Wait for async OSP instance creation to complete



- when: openstack_server_state != 'absent' | default(true)
  block:

     - name: Get Openstack server info
       os_server_info:
         cloud:     "{{ __openstack_server.openstack_cloud   | default('openstack') }}"
         server:      "{{ __openstack_server.instance_name }}"
       loop: "{{ openstack_servers }}"
       loop_control:
         loop_var: __openstack_server
       register: s_instances
     

     - name: Wait for servers by name to be available
       wait_for:
         host: "{{ __ip.1.private_v4 }}"
         port: 22
         search_regex: OpenSSH
         timeout: 600
       loop: "{{ s_instances.results|subelements('openstack_servers') }}"
       loop_control:
         loop_var: __ip
       delegate_to: "{{ inventory_hostname }}"
...

