---

- name: Generate inmemory inventory
  block:

    - name: Fetch Instance Info
      

    - name: Add host(s) to inventory
      


    - name: Output the in-memory inventory
      block:

      - name: Print hosts to STDOUT
        debug:
          msg:
            - "name: {{ __instance.private_v4 }}"
            - "group: {{ __instance.metadata.AnsibleGroup }}"
        loop: "{{ r_instances.openstack_servers }}"
        loop_control:
          loop_var: __instance
  tags:
    - openstack-inventory
    - must
